
[package]
name = "pxc"
version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.9"
ncurses = "6.0.1"
rand = "0.7.3"
